- name: Install required system packages
  ansible.builtin.package:
    pkg:
      - python3-pip
      - acl
    state: present
    update_cache: true

- name: Add PostgreSQL repository
  become: true
  ansible.builtin.shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  register: output
  changed_when: output.rc != 0

- name: Add PostgreSQL GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/postgresql.gpg

- name: Install PostgreSQL 16 and client
  become: true
  ansible.builtin.apt:
    name:
      - postgresql-16
      - postgresql-client-16
    state: present
    update_cache: true

- name: Enable and start PostgreSQL service
  become: true
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started

- name: Install Python libraries
  ansible.builtin.pip:
    name:
      - psycopg2-binary
