- name: Install required system packages
  ansible.builtin.package:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - net-tools
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.package:
    name: docker-ce
    state: present
    update_cache: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name:
      - docker==6.1.3
      - docker-compose